language: rust
rust:
  - 1.35.0 # Clippy fails on 1.34.2
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy
script:
  - cargo test --verbose
  - cargo clippy -- -D warnings
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
