language: rust
rust:
  - 1.31.1 # Version currently supported by Codeforces
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy
script:
  - cargo test --verbose
  - cargo clippy -- -D warnings
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
